 version: '3'
 services:
   db:
     image: postgres
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=pgdbuser
       - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   dva:
     build: .
     image: akshayubhat/dva-auto:latest
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - LAUNCH_SERVER=1
       - LAUNCH_BY_NAME_indexer_inception=1
       - LAUNCH_BY_NAME_indexer_facenet=1
       - LAUNCH_BY_NAME_retriever_inception=1
       - LAUNCH_BY_NAME_retriever_facenet=1
       - LAUNCH_BY_NAME_detector_coco=1
       - LAUNCH_BY_NAME_detector_face=1
       - LAUNCH_Q_qclusterer=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_SCHEDULER=1
       - TEST=1
       - AUTH_DISABLED=1
     command: bash -c "youtube-dl -U && git pull && fab start_container_server"
     ports:
       - "8000:8000"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
   dva-crnn:
     image: akshayubhat/dva-auto:latest
     container_name: dva-crnn
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - LAUNCH_BY_NAME_analyzer_crnn=1
       - PYTORCH_MODE=1
     command: bash -c "git pull && fab start_container_worker"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:

