 version: '3'
 services:
   db:
     image: postgres
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   dva:
     build: .
     image: akshayubhat/dva:gpu
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - ENABLE_YOLO=1
       - SCENEDETECT_DISABLE=1
     command: bash -c "youtube-dl -U && git pull && fab setup_container_gpu && fab launch_queues:1 && fab process_video_list:experiments/Driving/data.json && supervisord -n"
     ports:
       - "8000:80"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
   dvaw1:
     build: .
     image: aub3dva:gpu
     container_name: dva-worker-1
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - ENABLE_YOLO=1
       - SCENEDETECT_DISABLE=1
     command: bash -c "youtube-dl -U && git pull && fab startq:extractor"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
   dvaw2:
     build: .
     image: aub3dva:gpu
     container_name: dva-worker-2
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - ENABLE_YOLO=1
       - SCENEDETECT_DISABLE=1
     command: bash -c "youtube-dl -U && git pull && fab startq:extractor"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:

